Attribute VB_Name = "modGlobals"
Option Explicit
Public gconDMIS                                        As ADODB.Connection
Public gconACCESS                                      As ADODB.Connection
Public gconBIR_RELIEF                                  As ADODB.Connection
Public OVERWRAYT                                       As Boolean
Attribute OVERWRAYT.VB_VarUserMemId = 1073741827
Public LOGID                                           As String
Attribute LOGID.VB_VarUserMemId = 1073741828
Public LOGCODE                                         As String
Attribute LOGCODE.VB_VarUserMemId = 1073741829
Public LOGNAME                                         As String
Attribute LOGNAME.VB_VarUserMemId = 1073741830
Public LOGLEVEL                                        As String
Attribute LOGLEVEL.VB_VarUserMemId = 1073741831
Public LOGTIME                                         As String
Attribute LOGTIME.VB_VarUserMemId = 1073741832
Public LOGDATE                                         As String
Attribute LOGDATE.VB_VarUserMemId = 1073741833
Public LOGPASS                                         As String
Attribute LOGPASS.VB_VarUserMemId = 1073741834
Public LEDGERSHOW                                      As Boolean
Attribute LEDGERSHOW.VB_VarUserMemId = 1073741835
Public EMPINFOSHOW                                     As Boolean
Attribute EMPINFOSHOW.VB_VarUserMemId = 1073741836
Public HEADEMPINFOSHOW                                 As Boolean
Attribute HEADEMPINFOSHOW.VB_VarUserMemId = 1073741837
Public CASHOW                                          As Boolean
Attribute CASHOW.VB_VarUserMemId = 1073741838
Public GENFROM                                         As String
Attribute GENFROM.VB_VarUserMemId = 1073741839
Public GENTO                                           As String
Attribute GENTO.VB_VarUserMemId = 1073741840
Public HEADOREMP                                       As String
Attribute HEADOREMP.VB_VarUserMemId = 1073741841
Public HRMS_REPORT_PATH                                As String
Attribute HRMS_REPORT_PATH.VB_VarUserMemId = 1073741842
Public HRMS_PICTURES_PATH                              As String
Attribute HRMS_PICTURES_PATH.VB_VarUserMemId = 1073741843
Public Maxwiz                                          As Long
Attribute Maxwiz.VB_VarUserMemId = 1073741844
Public AccessCNT                                       As Long
Attribute AccessCNT.VB_VarUserMemId = 1073741845
Public wizVar                                          As Object
Attribute wizVar.VB_VarUserMemId = 1073741846
Public CryptVar                                        As Object
Attribute CryptVar.VB_VarUserMemId = 1073741847
Public EmpInfoEmpno                                    As Object
Attribute EmpInfoEmpno.VB_VarUserMemId = 1073741848
Public FormYearlyRequest                               As String
Attribute FormYearlyRequest.VB_VarUserMemId = 1073741849
Public OfficeHeadNo                                    As String
Attribute OfficeHeadNo.VB_VarUserMemId = 1073741850
Public Officehead                                      As String
Attribute Officehead.VB_VarUserMemId = 1073741851

