Attribute VB_Name = "modGlobals"
Option Explicit
Public GCONDMIS                                        As ADODB.Connection
Public GCONACCESS                                      As ADODB.Connection
Public GCONBIR_RELIEF                                  As ADODB.Connection
Public OVERWRAYT                                       As Boolean
Public LOGID                                           As String
Public LOGCODE                                         As String
Public LOGNAME                                         As String
Public LOGLEVEL                                        As String
Public LOGTIME                                         As String
Public LOGDATE                                         As String
Public LOGPASS                                         As String
Public LEDGERSHOW                                      As Boolean
Public EMPINFOSHOW                                     As Boolean
Public HEADEMPINFOSHOW                                 As Boolean
Public CASHOW                                          As Boolean
Public GENFROM                                         As String
Public GENTO                                           As String
Public HEADOREMP                                       As String
Public HRMS_REPORT_PATH                                As String
Public HRMS_PICTURES_PATH                              As String
Public MAXWIZ                                          As Long
Public ACCESSCNT                                       As Long
Public WIZVAR                                          As Object
Public CRYPTVAR                                        As Object
Public EMPINFOEMPNO                                    As Object
Public FORMYEARLYREQUEST                               As String
Public OFFICEHEADNO                                    As String
Public OFFICEHEAD                                      As String

