Attribute VB_Name = "modResources"
Public Const ID_FILE_NEW = 100
Public Const ID_FILE_OPEN = 101
Public Const ID_FILE_CLOSE = 102
Public Const ID_FILE_SAVE = 103
Public Const ID_FILE_EXIT = 104

Public Const ID_EDIT_UNDO = 105
Public Const ID_EDIT_COPY = 106
Public Const ID_EDIT_PASTE = 107
Public Const ID_EDIT_CUT = 108

Public Const ID_VIEW_TOOLBAR_STANDARD = 109
Public Const ID_VIEW_TOOLBAR_THEMES = 115
Public Const ID_VIEW_STATUSBAR = 110
Public Const ID_VIEW_OPTIONS = 111

Public Const ID_HELP_ABOUT = 112

Public Const ID_FILE_PRINT = 113
Public Const ID_FILE_PRINT_SETUP = 114

Public Const ID_THEME_CLIENTPANE = 130
Public Const ID_THEME_SHOWEXPANDBUTTON = 131

Public Const ID_THEME_OFFICE2000_PLAIN = 143
Public Const ID_THEME_OFFICEXP_PLAIN = 144
Public Const ID_THEME_OFFICE2003_PLAIN = 145
Public Const ID_THEME_NATIVE_PLAIN = 146

Public Const ID_TASKITEM_HIDECONTENTS = 1
Public Const ID_TASKITEM_ADDORREMOVE = 2
Public Const ID_TASKITEM_SEARCH = 3
Public Const ID_TASKITEM_NEWFOLDER = 4
Public Const ID_TASKITEM_PUBLISH = 5
Public Const ID_TASKITEM_SHARE = 6
Public Const ID_TASKITEM_MYCOMPUTER = 7
Public Const ID_TASKITEM_MYDOCUMENTS = 8

Public Const ID_SHORTCUT_SHOW_MORE = 300
Public Const ID_SHORTCUT_SHOW_FEWER = 301

Public Const FCONTROL = 8

