Attribute VB_Name = "modResources"
Public Const FILE_DEPARTMENT = 1105
Public Const FILE_EMPLOYEE = 1106
Public Const FILE_SIGNATORIES = 1107
Public Const FILE_SUPPLIER = 1104
Public Const FILE_SUPPLY = 1103
Public Const FILE_UNIT = 1108

Public Const INQUIRY_SUPPLIESISSUED = 1120
Public Const INQUIRY_SUPPLIESRECEIVED = 1119
Public Const INQUIRY_SUPPLYINVENTORY = 1121

Public Const MAINTAINENANCE_PASSWORDMAINTENANCE = 1127

Public Const PROCEESING_MONTHEND_BATCHPOSTING = 1115
Public Const PROCESSING_CHECKPREVIOUSBALANCE = 1114
Public Const PROCESSING_MONTHEND_CREATESTOCKSTATUS = 1117
Public Const PROCESSING_MONTHEND_GENERATERANKFILE = 1118
Public Const PROCESSING_MONTHEND_MONTHPROCESS = 1116
Public Const PROCESSING_UPDATEINVENTORYADJUSTMENTS = 1113
Public Const PROCESSING_UPDATESUPPLIESMASTERFILE = 1112

Public Const REPORTS_MONTHLYISSUANCEBYDEPARTMENT = 1124
Public Const REPORTS_MONTHLYRECEIPTSBYSUPPLIER = 1126
Public Const REPORTS_SUPPLYINVENTORYRANKING = 1122
Public Const REPORTS_SUPPLYSTATUSREPORT = 1123

Public Const TRANSACTION_RECEIVINGSUPPLY = 1109
Public Const TRANSACTION_SUPPLIESINVENTORYADJUSTMENT = 1111
Public Const TRANSACTION_SUPPLYISSUANCE = 1110

Public Const WINDOW_ABOUT = 1128
Public Const WINDOW_EXITOSMS = 1129

