Attribute VB_Name = "modResources"
Public Const EMP_INFO_ALLOWANCEBASEEMPLOYEES = 1027
Public Const EMP_INFO_CONTRACTUALINFO = 1026
Public Const EMP_INFO_EMPLOYEEINFO = 1025
Public Const EMP_INFO_MANAGERSINFO = 1028
Public Const EMP_LEDGER = 1036
Public Const EMP_MAINTAIN_ADJUSTMENT = 1035
Public Const EMP_MAINTAIN_ATMENTRY = 1034
Public Const EMP_MAINTAIN_ATTENDANCE = 1029
Public Const EMP_MAINTAIN_COMMISSION = 1033
Public Const EMP_MAINTAIN_DEDUCTIONS = 1032
Public Const EMP_MAINTAIN_OVERTIME = 1031
Public Const EMP_MAINTAIN_SALARYADVANCE = 1030
Public Const FILES_DEPARTMENT = 1023
Public Const FILES_GROUPS = 1024
Public Const FILES_PHILHEALTHBRACKETING = 1021
Public Const FILES_SALARYGRADECODES = 1022
Public Const FILES_SSSBRACKETING = 1020
Public Const MAINTAIN_COMPANYPROFILE = 1071
Public Const MAINTAIN_PASSWORDMAINTENANCE = 1073
Public Const MAINTAIN_USERMODULES = 1072
Public Const PROCESS_BIRALPHALISTPROCESSING = 1039
Public Const PROCESS_GENERATEPAYROLL = 1037
Public Const PROCESS_UPDATEATTENDANCE = 1041
Public Const PROCESS_UPDATECOMMISSION = 1040
Public Const PROCESS_YEARTODATEPROCESSING = 1038
Public Const RPT_ALPHA_ALPHALISTOFEMPLOYEESWITHPREVIOUSEMPLOYERWITHINAYEAR = 1043
Public Const RPT_ALPHA_ALPHALISTOFTERMINATEDEMPLOYEESBEFOREDECEMBER = 1042
Public Const RPT_ALPHA_ID_ALPHALISTOFEMPLOYEESWITHNOPREVIOUSEMPLOYERWITHINAYEAR = 1044
Public Const RPT_ALPHA_OTHER_LOANSMASTERFILELISTING = 1048
Public Const RPT_ALPHA_OTHER_RESIGNEESLISTING = 1047
Public Const RPT_ALPH_OTHER_EMPLOYEELISTING = 1045
Public Const RPT_ALPH_OTHER_EMPLOYEELISTINGWAGE = 1046
Public Const RPT_MISC_PRINTBLANKEMPLOYEEINFOSHEET = 1067
Public Const RPT_MONTH_LOANSMONTHLYREMITTANCE = 1053
Public Const RPT_MONTH_PAGIBIGMONTHLYREMITTANCE = 1052
Public Const RPT_MONTH_PHILHEALTHMONTHLYREMITTANCE = 1051
Public Const RPT_MONTH_PRINTMONTHLYPAYROLL = 1054
Public Const RPT_MONTH_SSSMONTHLYREMITTANCE = 1050
Public Const RPT_MONTH_WITHHOLDINGTAXMONTHLYREMITTANCE = 1049
Public Const RPT_PRINTATMADVICE = 1069
Public Const RPT_PRINTPAYROLLJOURNAL = 1070
Public Const RPT_PRINTPAYROLLSHEET = 1068
Public Const RPT_SCHD_SCHEDULEOFCOMMISSION = 1061
Public Const RPT_SCHD_SCHEDULEOFCOMMISSIONTAX = 1062
Public Const RPT_SCHD_SCHEDULEOFOVERTIMEPAY = 1059
Public Const RPT_SCHD_SCHEDULEOFPAGIBIGPREMIUMCONTRIBUTION = 1057
Public Const RPT_SCHD_SCHEDULEOFPAYROLL = 1060
Public Const RPT_SCHD_SCHEDULEOFPHILHEALTHPREMIUMCONTRIBUTION = 1056
Public Const RPT_SCHD_SCHEDULEOFSSSPREMIUMCONTRIBUTION = 1055
Public Const RPT_SCHD_SCHEDULEOFTAXDUEREFUND = 1064
Public Const RPT_SCHD_SCHEDULEOFTAXWITHHELD = 1058
Public Const RPT_SCHD_THMONTHPAYSCHEDULE = 1063
Public Const RPT_SUMMARY_DEDUCTIONDETAILS = 1065
Public Const RPT_SUMMARY_YEARTODATEDETAILS = 1066
Public Const TOOL_CALCULATOR = 1075
Public Const TOOL_CALENDAR = 1074
Public Const TOOL_COMPACTREPAIRDATABASE = 1077
Public Const TOOL_ZIPBACKUPDATABASE = 1076
Public Const WINDOW_ABOUTTHEAUTHOR = 1080
Public Const WINDOW_ARRANGEWINDOWS = 1079
Public Const WINDOW_EXIT = 1081



Public Const TOOL_EMPLOYEEINFORMATION = 1083
Public Const TOOL_NUMBEROFDAYS = 1084
Public Const TOOL_OVERTIME = 1085
Public Const TOOL_DEDUCTION = 1086
Public Const TOOL_COMMISSION = 1087
Public Const TOOL_ADJUSTMENT = 1088
Public Const TOOL_ATMDETAILS = 1089
Public Const TOOL_LEDGER = 1102
Public Const TOOL_GENERATEPAYROLL = 1091
Public Const TOOL_YEARTODATEPROCESSING = 1092
Public Const TOOL_PRINTPAYROLLSHEET = 1093
Public Const TOOL_PRINTATMADVICE = 1094
Public Const TOOL_WITHOLDINGTAXMONTHLYREMITTANCE = 1095
Public Const TOOL_SSSMONTHLYREMITTANCE = 1096
Public Const TOOL_PHILHEALTHMONTHLYREMITTANCE = 1097
Public Const TOOL_PAGIBIGMONTHLYREMITTANCE = 1098
Public Const TOOL_SSSLOANREMITTANCE = 1099
Public Const TOOL_ABOUTTHEAUTHOR = 1100
Public Const TOOL_EXITHRMS = 1101
Public Const TOOL_DASHBOARD = 1103
Public Const RPT_RSSS = 1128














