Attribute VB_Name = "modResources"
Public Const FIILES_SERVICE_TECHNICIAN = 1022
Public Const FILES_COUNTER = 1028
Public Const FILES_CUSTOMERCONTROL = 1029
Public Const FILES_CUSTOMERMASTERLIST = 1020
Public Const FILES_SERVICE_CANNEDLABOR = 1025
Public Const FILES_SERVICE_GENERALJOBS = 1023
Public Const FILES_SERVICE_MATERIALSMASTERLIST = 1027
Public Const FILES_SERVICE_MODEL = 1026
Public Const FILES_SERVICE_PMSJOBS = 1024
Public Const FILES_SERVICE_SERVICEADVISOR = 1021

Public Const INQUIRY_CUSTOMERVEHICLEINQUIRY = 1042
Public Const INQUIRY_JOBESTIMATELISTING = 1047
Public Const INQUIRY_LISTBYINVOICENUMBER = 1045
Public Const INQUIRY_LISTBYPLATENUMBER = 1046
Public Const INQUIRY_LISTBYREPAIRORDER = 1044
Public Const INQUIRY_PARTSINQUIRY = 1048
Public Const INQUIRY_PARTSLISTING = 1049
Public Const INQUIRY_SERVICEADVISORSWORKDETAILS = 1043

Public Const MAINTAIN_COMPANYPROFILE = 1055
Public Const MAINTAIN_EXPORTDATANOW = 1059
Public Const MAINTAIN_PASSWORDMAINTENANCE = 1057
Public Const MAINTAIN_TRANSFERDATANOW = 1058
Public Const MAINTAIN_USERMODULES = 1056

Public Const MATINV_CASHCOUNTERISSUANCE = 1034
Public Const MATINV_CHARGECOUNTERISSUANCE = 1035
Public Const MATINV_DROUTISSUANCE = 1037
Public Const MATINV_MATPROCESS_UPDATEMASTERFILE = 1041
Public Const MATINV_MATQRY_CHECKPREVIOUSBALANCE = 1039
Public Const MATINV_MATQRY_MATERIALSLISTING = 1040
Public Const MATINV_RECEIVINGSTORING = 1038
Public Const MATINV_REQUISITIONISSUANCESLIP = 1036

Public Const RPT_CUSTOMERDIRECTORYLISTING = 1050
Public Const RPT_SERVICEREPORT = 1054
Public Const RPT_TECHNICIANLABOREFFICIENCY = 1051
Public Const RPT_TRANSACTIONSFORFOLLOWUP = 1052
Public Const RPT_VEHICLEBYMODEL = 1053

Public Const TRANS_BILLINGSYSTEM = 1033
Public Const TRANS_JOBESTIMATE = 1031
Public Const TRANS_REPAIRORDER = 1032
Public Const TRANS_SERVICECOUNTER = 1030

Public Const WINDOW_ABOUT = 1060
Public Const WINDWO_EXIT = 1061

